In [ ]:
# example indexing

import torch as t

n_vecs = 5

vecs = t.arange(n_vecs * 2).reshape(n_vecs, 2)

selector = t.tensor([True] + [False] * (n_vecs - 2) + [True])

print(vecs)
print(selector)
print(vecs[selector])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([ True, False, False, False,  True])
tensor([[0, 1],
        [8, 9]])


# Some torch stuff

In [9]:
# untyped storage shows bytes
import torch as t


x = t.tensor([1, 2, 4])

# 3 x 8 bytes
print(x.untyped_storage())

 1
 0
 0
 0
 0
 0
 0
 0
 2
 0
 0
 0
 0
 0
 0
 0
 4
 0
 0
 0
 0
 0
 0
 0
[torch.storage.UntypedStorage(device=cpu) of size 24]


In [14]:
import einops as ein

y = ein.repeat(x, "h -> h 7")
print(x)
print(y)
# repeating does not necessarily increase the storage <3
print(y.untyped_storage())

tensor([1, 2, 4])
tensor([[1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2],
        [4, 4, 4, 4, 4, 4, 4]])
 1
 0
 0
 0
 0
 0
 0
 0
 2
 0
 0
 0
 0
 0
 0
 0
 4
 0
 0
 0
 0
 0
 0
 0
[torch.storage.UntypedStorage(device=cpu) of size 24]


In [16]:
# get the original tensor with base
y._base

tensor([1, 2, 4])

In [ ]:
# split tensor into components with unbind

x = t.arange(10).reshape(2, 5)

print(x)

a, b = x
print(a)
print(b)


c0, c1, c2, c3, c4 = t.unbind(x, dim=1)
print(c0)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])
tensor([0, 5])


# DK divergence

In [6]:
import math


def d_kl(p, q):
    assert len(p) == len(q)

    divergence = 0
    for i in range(len(p)):
        divergence += p[i] * math.log(p[i] / q[i])

    return divergence

In [12]:
p = (0.1, 0.9)
q = (0.01, 0.99)

print(f"d_KL(p||q): {d_kl(p,q)}")
print(f"d_KL(q||p): {d_kl(q,p)}")

d_KL(p||q): 0.14447934747551233
d_KL(q||p): 0.07133122707634103


In [ ]:
p = (0.1, 0.9)

p_q = []
q_p = []
for e in range(1, 10):
    q = (0.1**e, 1 - 0.1**e)
    p_q.append(d_kl(p, q))
    q_p.append(d_kl(q, p))


import plotly.graph_objects as go

# Assuming d_kl is defined and p_q, q_p are computed
e_values = list(range(1, 10))  # x-axis values

fig = go.Figure()

# Add traces for p_q and q_p
fig.add_trace(
    go.Scatter(
        x=e_values,
        y=p_q,
        mode="lines+markers",
        name="D_KL(P || Q)",
        line=dict(color="blue"),
    )
)

fig.add_trace(
    go.Scatter(
        x=e_values,
        y=q_p,
        mode="lines+markers",
        name="D_KL(Q || P)",
        line=dict(color="red"),
    )
)

# Update layout
fig.update_layout(
    title="KL Divergence for Different Values of e",
    xaxis_title="e",
    yaxis_title="D_KL",
    legend_title="Divergence",
    template="plotly_white",
)

fig.show()

## Model weihgts

In [ ]:
import torch as t
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(5, 10),
    nn.ReLU(),
    nn.Linear(10, 2),
)

model = nn.Linear(2, 3)
model(t.tensor([1.0, 2.0])).sum().backward()

for p in model.parameters():
    print(p)
    print(p.grad)

Parameter containing:
tensor([[-0.2402,  0.4450],
        [ 0.1989,  0.4980],
        [-0.5973, -0.6177]], requires_grad=True)
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])
Parameter containing:
tensor([ 0.2637, -0.1992, -0.3264], requires_grad=True)
tensor([1., 1., 1.])


## Git stuff

In [8]:
from git import Repo

repo = Repo()
git_username = repo.config_reader().get_values(section="user", option="name")[0]
git_email = repo.config_reader().get_values(section="user", option="email")[0]
print(git_username)
print(git_email)

julxi
bitt.j@protonmail.com
