In [ ]:
# example indexing

import torch as t

n_vecs = 5

vecs = t.arange(n_vecs * 2).reshape(n_vecs, 2)

selector = t.tensor([True] + [False] * (n_vecs - 2) + [True])

print(vecs)
print(selector)
print(vecs[selector])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([ True, False, False, False,  True])
tensor([[0, 1],
        [8, 9]])


# Some torch stuff

In [9]:
# untyped storage shows bytes
import torch as t


x = t.tensor([1, 2, 4])

# 3 x 8 bytes
print(x.untyped_storage())

 1
 0
 0
 0
 0
 0
 0
 0
 2
 0
 0
 0
 0
 0
 0
 0
 4
 0
 0
 0
 0
 0
 0
 0
[torch.storage.UntypedStorage(device=cpu) of size 24]


In [14]:
import einops as ein

y = ein.repeat(x, "h -> h 7")
print(x)
print(y)
# repeating does not necessarily increase the storage <3
print(y.untyped_storage())

tensor([1, 2, 4])
tensor([[1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2],
        [4, 4, 4, 4, 4, 4, 4]])
 1
 0
 0
 0
 0
 0
 0
 0
 2
 0
 0
 0
 0
 0
 0
 0
 4
 0
 0
 0
 0
 0
 0
 0
[torch.storage.UntypedStorage(device=cpu) of size 24]


In [16]:
# get the original tensor with base
y._base

tensor([1, 2, 4])

In [ ]:
# split tensor into components with unbind

x = t.arange(10).reshape(2, 5)

print(x)

a, b = x
print(a)
print(b)


c0, c1, c2, c3, c4 = t.unbind(x, dim=1)
print(c0)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])
tensor([0, 5])
